# Generated by Django 5.0.6 on 2024-05-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thirukkural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('couplet', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
            ],
        ),
    ]
