# Generated by Django 5.0.6 on 2024-05-31 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kural', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thirukkural',
            old_name='explanation',
            new_name='meaning',
        ),
    ]
