# Generated by Django 5.0.6 on 2024-05-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kural', '0002_rename_explanation_thirukkural_meaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirukkural',
            name='couplet',
            field=models.CharField(max_length=500),
        ),
    ]
